FROM python:3.12-slim

WORKDIR /app

COPY eckert4/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY eckert4/app ./app
COPY eckert4/app/crawler ./app/crawler
COPY eckert4/app/models ./app/models
COPY eckert4/app/consumers ./app/consumers
COPY eckert4/app/config.py ./app/config.py
COPY eckert4/app/main.py ./app/main.py

EXPOSE 8000

ENTRYPOINT ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--log-level", "debug"] 